"use client";
/* eslint-disable @next/next/no-img-element -- tournament images may be data URLs */
import Link from "next/link"; import { useEffect, useState } from "react";
import { useAuth } from "@/hooks/useAuth"; import { api } from "@/lib/api"; import type { Tournament } from "@/lib/types";
import { Badge } from "@/ui/Badge"; import { Card } from "@/ui/Card";

export default function TournamentsPage(){const {user,loading}=useAuth();const [items,setItems]=useState<Tournament[]>([]);useEffect(()=>{if(user)api.myTournaments().then(setItems).catch(()=>setItems([]));},[user]);
 if(loading)return <div className="py-24 text-center text-muted">Loading…</div>;
 if(!user)return <div className="mx-auto max-w-xl px-4 py-24 text-center"><h1 className="text-2xl font-bold">Create tournaments</h1><p className="mt-2 text-muted">Log in or create an account to save drafts and submit them for approval.</p><Link href="/auth" className="mt-6 inline-flex rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white">Log in or sign up</Link></div>;
 return <div className="mx-auto max-w-6xl px-4 py-10"><div className="mb-8 flex items-center justify-between"><div><h1 className="text-2xl font-bold">Your tournaments</h1><p className="mt-1 text-sm text-muted">Continue drafts and track submitted or previously approved tournaments.</p></div><Link href="/tournaments/new" className="rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white">+ New tournament</Link></div>
 <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map(t=><Link key={t.id} href={t.approvalStatus==="draft"||t.approvalStatus==="rejected"?`/tournaments/${t.id}/edit`:`/organizer?tournamentId=${t.id}`}><Card className="overflow-hidden transition-colors hover:border-accent/50"><img src={t.imageUrl||"/tournament-placeholder.svg"} alt="" className="h-36 w-full object-cover"/><div className="p-4"><div className="flex justify-between gap-2"><h2 className="font-semibold">{t.name}</h2><Badge tone={t.approvalStatus==="approved"?"accent":"muted"}>{t.approvalStatus}</Badge></div><p className="mt-2 text-sm text-muted">{t.sport} · {t.teams.length} teams</p>{t.rejectionReason&&<p className="mt-2 text-sm text-red-700">{t.rejectionReason}</p>}</div></Card></Link>)}{!items.length&&<div className="col-span-full rounded-xl border border-dashed border-border py-16 text-center text-muted">No drafts yet.</div>}</div></div>}
