"use client";
/* eslint-disable @next/next/no-img-element -- previews may be local data URLs */

import { useCallback, useEffect, useState } from "react"; import { useRouter } from "next/navigation"; import Link from "next/link";
import { useAuth } from "@/hooks/useAuth"; import { api } from "@/lib/api"; import type { Player, Sport, Tournament } from "@/lib/types";
import { SPORTS, SPORT_LABEL } from "@/lib/format"; import { Button } from "@/ui/Button"; import { Card, CardBody, CardHeader, CardTitle } from "@/ui/Card"; import { Field } from "@/ui/Field"; import { Input, Select } from "@/ui/Input";

const RULES:Record<Sport,{players:string;teams:string}>={cricket:{players:"11–15 players per team",teams:"2–16 teams"},football:{players:"11–23 players per team",teams:"2–32 teams"},basketball:{players:"5–15 players per team",teams:"2–32 teams"}};

export function TournamentEditor({tournamentId}:{tournamentId?:number}){
 const {user,loading}=useAuth();const router=useRouter();const [t,setT]=useState<Tournament|null>(null);const [players,setPlayers]=useState<Player[]>([]);const [name,setName]=useState("");const [sport,setSport]=useState<Sport>("cricket");const [format,setFormat]=useState("league");const [imageUrl,setImageUrl]=useState<string|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const refresh=useCallback(async()=>{if(!tournamentId)return;const data=await api.getTournament(tournamentId);setT(data);setName(data.name);setSport(data.sport);setFormat(data.format||"league");setImageUrl(data.imageUrl);},[tournamentId]);
 useEffect(()=>{if(!user)return;const timer=window.setTimeout(()=>{refresh().catch(e=>setError(e.message));api.myPlayers().then(setPlayers).catch(()=>{});},0);return()=>window.clearTimeout(timer)},[user,refresh]);
 function photo(file?:File){if(!file)return;if(file.size>2_000_000){setError("Photo must be smaller than 2 MB");return;}const reader=new FileReader();reader.onload=()=>setImageUrl(String(reader.result));reader.readAsDataURL(file)}
 async function saveDetails(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{if(t){const updated=await api.updateTournament(t.id,{name,sport,format,imageUrl});setT(updated);}else{const created=await api.createTournament({name,sport,format,imageUrl});router.replace(`/tournaments/${created.id}/edit`);}}catch(e){setError(e instanceof Error?e.message:"Could not save draft");}finally{setBusy(false)}}
 if(loading)return <div className="py-24 text-center text-muted">Loading…</div>;if(!user)return <div className="py-24 text-center"><p className="text-muted">You need an account to create a draft.</p><Link href="/auth" className="mt-4 inline-flex rounded-lg bg-accent px-4 py-2 font-semibold text-black">Log in or sign up</Link></div>;
 return <div className="mx-auto max-w-5xl px-4 py-10"><div className="mb-8"><p className="text-sm font-medium text-accent">Tournament builder</p><h1 className="mt-1 text-2xl font-bold">{t?"Edit tournament draft":"Create a tournament"}</h1><p className="mt-2 text-sm text-muted">Your progress stays in draft until you submit it for admin review.</p></div>{error&&<p className="mb-5 rounded-lg bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}
 <div className="grid gap-6 lg:grid-cols-[320px_1fr]"><Card className="h-fit"><CardHeader><CardTitle>Tournament details</CardTitle></CardHeader><CardBody><form onSubmit={saveDetails} className="space-y-4"><img src={imageUrl||"/tournament-placeholder.svg"} alt="Tournament preview" className="h-36 w-full rounded-lg object-cover"/><Field label="Tournament photo" hint="Optional; a placeholder is used if empty."><Input type="file" accept="image/*" onChange={e=>photo(e.target.files?.[0])}/></Field><Field label="Tournament name"><Input value={name} onChange={e=>setName(e.target.value)} required/></Field><Field label="Sport"><Select value={sport} onChange={e=>setSport(e.target.value as Sport)} disabled={Boolean(t?.teams.length)}>{SPORTS.map(s=><option key={s} value={s}>{SPORT_LABEL[s]}</option>)}</Select></Field><Field label="Format"><Select value={format} onChange={e=>setFormat(e.target.value)}><option value="league">League</option><option value="knockout">Knockout</option></Select></Field><div className="rounded-lg bg-surface-2 p-3 text-xs text-muted"><strong className="text-foreground">{SPORT_LABEL[sport]} rules:</strong><br/>{RULES[sport].teams} · {RULES[sport].players}</div><Button type="submit" className="w-full" disabled={busy}>{busy?"Saving…":t?"Save details":"Save draft & add teams"}</Button></form></CardBody></Card>
 <div>{!t?<div className="rounded-xl border border-dashed border-border py-20 text-center text-sm text-muted">Save the tournament details to start adding teams and players.</div>:<DraftTeams tournament={t} savedPlayers={players} refresh={refresh} refreshPlayers={()=>api.myPlayers().then(setPlayers)} setError={setError}/>}</div></div></div>
}

function DraftTeams({tournament,savedPlayers,refresh,refreshPlayers,setError}:{tournament:Tournament;savedPlayers:Player[];refresh:()=>Promise<void>;refreshPlayers:()=>void;setError:(s:string)=>void}){
 const [teamName,setTeamName]=useState("");const [shortName,setShortName]=useState("");const [busy,setBusy]=useState(false);
 async function addTeam(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api.addTournamentTeam(tournament.id,{name:teamName,shortName});setTeamName("");setShortName("");await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not add team");}finally{setBusy(false)}}
 async function submit(){setBusy(true);try{await api.submitTournament(tournament.id);await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not submit");}finally{setBusy(false)}}
 if(tournament.approvalStatus==="submitted")return <Card><CardBody className="py-16 text-center"><h2 className="text-xl font-semibold">Submitted for review</h2><p className="mt-2 text-sm text-muted">An admin will approve or reject this tournament. Editing is paused while it is under review.</p><Link href="/tournaments" className="mt-5 inline-block text-sm font-medium text-accent">Back to your tournaments</Link></CardBody></Card>;
 return <div className="space-y-5"><Card><CardHeader><CardTitle>Teams</CardTitle><p className="mt-1 text-sm text-muted">Add each participating team, then build its roster.</p></CardHeader><CardBody><form onSubmit={addTeam} className="grid gap-3 sm:grid-cols-[1fr_120px_auto]"><Input placeholder="Team name" value={teamName} onChange={e=>setTeamName(e.target.value)} required/><Input placeholder="Short name" maxLength={5} value={shortName} onChange={e=>setShortName(e.target.value)} required/><Button type="submit" disabled={busy}>Add team</Button></form></CardBody></Card>
 {tournament.teams.map(({team})=><TeamEditor key={team.id} tournament={tournament} team={team} savedPlayers={savedPlayers} refresh={refresh} refreshPlayers={refreshPlayers} setError={setError}/>)}
 {tournament.teams.length>0&&<div className="flex items-center justify-between rounded-xl border border-border bg-surface p-5"><div><p className="font-semibold">Ready for review?</p><p className="text-sm text-muted">Submission checks team and roster sizes for {tournament.sport}.</p></div><Button onClick={submit} disabled={busy}>Submit tournament</Button></div>}</div>
}

function TeamEditor({tournament,team,savedPlayers,refresh,refreshPlayers,setError}:{tournament:Tournament;team:NonNullable<Tournament["teams"]>[number]["team"];savedPlayers:Player[];refresh:()=>Promise<void>;refreshPlayers:()=>void;setError:(s:string)=>void}){
 const [name,setName]=useState(team.name);const [short,setShort]=useState(team.shortName);const [playerId,setPlayerId]=useState("");const [newName,setNewName]=useState("");const [jersey,setJersey]=useState("");const [position,setPosition]=useState("");const [busy,setBusy]=useState(false);
 async function saveTeam(){setBusy(true);try{await api.updateTournamentTeam(tournament.id,team.id,{name,shortName:short});await refresh();}catch(e){setError(e instanceof Error?e.message:"Could not update team");}finally{setBusy(false)}}
 async function addPlayer(e:React.FormEvent){e.preventDefault();setBusy(true);try{await api.addTeamPlayer(tournament.id,team.id,{playerId:playerId?Number(playerId):undefined,name:playerId?undefined:newName,jerseyNumber:jersey,position});setPlayerId("");setNewName("");setJersey("");setPosition("");await refresh();refreshPlayers();}catch(e){setError(e instanceof Error?e.message:"Could not add player");}finally{setBusy(false)}}
 return <Card><CardHeader><div className="flex items-center justify-between gap-3"><div className="flex flex-1 gap-2"><Input value={name} onChange={e=>setName(e.target.value)}/><Input className="max-w-24" value={short} onChange={e=>setShort(e.target.value)} maxLength={5}/><Button variant="outline" onClick={saveTeam} disabled={busy}>Save</Button></div><button className="text-xs text-red-600" onClick={async()=>{await api.removeTournamentTeam(tournament.id,team.id);await refresh()}}>Remove</button></div></CardHeader><CardBody><div className="mb-4 space-y-2">{team.players?.map(tp=><div key={tp.playerId} className="flex items-center justify-between rounded-lg bg-surface-2 px-3 py-2 text-sm"><span><strong>#{tp.jerseyNumber}</strong> {tp.player.name}{tp.position?` · ${tp.position}`:""}</span><button className="text-xs text-red-600" onClick={async()=>{await api.removeTeamPlayer(tournament.id,team.id,tp.playerId);await refresh()}}>Remove</button></div>)}{!team.players?.length&&<p className="text-sm text-muted">No players added yet.</p>}</div><form onSubmit={addPlayer} className="grid gap-3 sm:grid-cols-2"><Select value={playerId} onChange={e=>setPlayerId(e.target.value)}><option value="">Create new player</option>{savedPlayers.filter(p=>!team.players?.some(tp=>tp.playerId===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</Select>{!playerId&&<Input placeholder="Player name" value={newName} onChange={e=>setNewName(e.target.value)} required/>}<Input placeholder="Jersey number" value={jersey} onChange={e=>setJersey(e.target.value)} required/><Input placeholder="Position (optional)" value={position} onChange={e=>setPosition(e.target.value)}/><Button type="submit" disabled={busy}>Add player</Button></form></CardBody></Card>
}
