"use client";

import { useCallback, useEffect, useState } from "react"; import Link from "next/link";
import { api } from "@/lib/api"; import type { Match } from "@/lib/types"; import { useAuth } from "@/hooks/useAuth"; import { useSocket } from "@/hooks/useSocket";
import { Button } from "@/ui/Button"; import { Card, CardBody, CardHeader, CardTitle } from "@/ui/Card"; import { Field } from "@/ui/Field"; import { Input, Select } from "@/ui/Input"; import { Badge, LiveBadge } from "@/ui/Badge";
import { useParams } from "next/navigation";

const CHECKS=[
 {key:"networkStable",label:"Stable upload tested",hint:"Run a field test; keep at least 8 Mbps sustained upload per phone."},
 {key:"powerReady",label:"Power and battery ready",hint:"Phones are charged, external power is connected, and overheating is managed."},
 {key:"audioChecked",label:"Audio monitored",hint:"Commentary/ambient audio is clean and only one primary audio source is active."},
 {key:"permissionsConfirmed",label:"Permissions confirmed",hint:"Venue, teams, and participants have approved the broadcast."},
 {key:"cameraOperatorsReady",label:"Camera operators briefed",hint:"Operators know their angle, stream name, kickoff time, and fallback plan."},
] as const;

export default function FootballMatchControl(){
 const route=useParams<{id:string}>();const id=Number(route.id);const {user,loading}=useAuth();const {socket}=useSocket();const [match,setMatch]=useState<Match|null>(null);const [venue,setVenue]=useState("");const [scheduledAt,setScheduledAt]=useState("");const [checks,setChecks]=useState<Record<string,boolean>>({});const [cameraName,setCameraName]=useState("");const [angle,setAngle]=useState("Main sideline");const [scoreA,setScoreA]=useState(0);const [scoreB,setScoreB]=useState(0);const [half,setHalf]=useState(1);const [minute,setMinute]=useState(0);const [extraTimeMinute,setExtraTimeMinute]=useState(0);const [eventType,setEventType]=useState("goal");const [playerQuery,setPlayerQuery]=useState("");const [selectedPlayerId,setSelectedPlayerId]=useState<number|null>(null);const [error,setError]=useState("");const [success,setSuccess]=useState("");const [busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!id)return;const data=await api.getMatch(id);setMatch(data);setVenue(data.venue||"");setScheduledAt(data.scheduledAt?new Date(data.scheduledAt).toISOString().slice(0,16):"");setChecks(data.broadcastChecklist||{});setScoreA(data.state.teamAScore);setScoreB(data.state.teamBScore);},[id]);
 useEffect(()=>{if(!user||!id)return;const timer=window.setTimeout(()=>load().catch(e=>setError(e.message)),0);return()=>clearTimeout(timer)},[user,id,load]);
 async function saveSetup(){if(!match)return;setBusy(true);setError("");try{setMatch(await api.updateBroadcastSetup(match.id,{venue,scheduledAt,checklist:checks}))}catch(e){setError(e instanceof Error?e.message:"Could not save setup")}finally{setBusy(false)}}
 async function addCamera(e:React.FormEvent){e.preventDefault();if(!match)return;setBusy(true);try{setMatch(await api.addMatchCamera(match.id,{name:cameraName,angle}));setCameraName("")}catch(e){setError(e instanceof Error?e.message:"Could not add camera")}finally{setBusy(false)}}
 async function start(){if(!match)return;setBusy(true);setError("");try{await api.updateBroadcastSetup(match.id,{venue,scheduledAt,checklist:checks});setMatch(await api.setMatchStatus(match.id,"live"))}catch(e){setError(e instanceof Error?e.message:"Could not start match")}finally{setBusy(false)}}
 function switchCamera(streamKey:string){if(!match)return;socket.emit("camera:switch",{matchId:match.id,cameraId:streamKey},(ack:{ok:boolean;error?:string})=>{if(!ack.ok)setError(ack.error||"Camera switch failed");else setMatch(current=>current?{...current,activeCamera:streamKey as Match["activeCamera"]}:current)})}
 function updateScorecard(){if(!match||!selectedPlayerId)return;const roster=[...(match.teamA.players||[]).map(player=>({...player,team:match.teamA})),...(match.teamB.players||[]).map(player=>({...player,team:match.teamB}))];const selected=roster.find(player=>player.playerId===selectedPlayerId);if(!selected)return;setBusy(true);setError("");setSuccess("");socket.emit("score:update",{matchId:match.id,sport:"football",state:{teamAScore:scoreA,teamBScore:scoreB,period:half,periodLabel:`${minute}${extraTimeMinute?`+${extraTimeMinute}`:""}'`,status:"live",extra:{minute,extraTimeMinute}},detail:{half,minute,extraTimeMinute,eventType,teamId:selected.team.id,playerId:selected.playerId}},(ack:{ok:boolean;error?:string;state?:Match["state"]})=>{setBusy(false);if(!ack.ok)setError(ack.error||"Scorecard update failed");else{if(ack.state){setScoreA(ack.state.teamAScore);setScoreB(ack.state.teamBScore)}setSelectedPlayerId(null);setPlayerQuery("");setSuccess("Scorecard updated for all viewers.");load()}})}
 if(loading||!id)return <div className="py-24 text-center text-muted">Loading…</div>;if(!user)return <div className="py-24 text-center"><Link href="/auth" className="text-accent">Log in to manage this match</Link></div>;if(!match)return <div className="py-24 text-center text-muted">{error||"Loading match…"}</div>;
 const completed=CHECKS.filter(c=>checks[c.key]).length;const ready=Boolean(venue&&scheduledAt&&match.cameras.length&&completed===CHECKS.length);
 const blockers=[...(!scheduledAt?["Set the kickoff time"]:[]),...(!venue?["Add the match venue"]:[]),...(match.cameras.length===0?["Add at least one camera"]:[]),...CHECKS.filter(c=>!checks[c.key]).map(c=>c.label)];
 return <div className="mx-auto max-w-6xl px-4 py-8"><Link href="/organizer" className="text-sm text-muted hover:text-foreground">← Organiser workspace</Link><div className="mt-5 flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2">{match.status==="live"?<LiveBadge/>:<Badge tone="muted">Pre-match</Badge>}<span className="text-sm text-muted">Football</span></div><h1 className="mt-2 text-2xl font-bold">{match.teamA.name} vs {match.teamB.name}</h1><p className="mt-1 text-sm text-muted">Prepare the broadcast, then run cameras and the scorecard from this page.</p></div>{match.status==="live"&&<Link href={`/matches/${match.id}`} className="rounded-lg border border-border px-4 py-2 text-sm font-medium text-foreground hover:bg-surface-2">Open public stream ↗</Link>}</div>{error&&<p className="mt-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 {match.status!=="live"&&<Card className={`mt-6 border-2 ${ready?"border-accent bg-accent/5":"border-border"}`}><CardBody><div className="flex flex-col gap-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-accent">Broadcast launch</p><h2 className="mt-1 text-lg font-semibold">{ready?"Everything is ready":"Complete setup before going live"}</h2>{ready?<p className="mt-1 text-sm text-muted">Your camera is configured. Starting makes this match visible as live on the public homepage.</p>:<ul className="mt-3 grid gap-1 text-sm text-muted sm:grid-cols-2">{blockers.map(item=><li key={item}>○ {item}</li>)}</ul>}</div><Button size="lg" onClick={start} disabled={busy||!ready} className="shrink-0">{busy?"Starting…":"Go live"}</Button></div></CardBody></Card>}
 <div className="mt-8 grid gap-6 lg:grid-cols-2"><div className="space-y-6"><Card><CardHeader><CardTitle>1. Match details</CardTitle></CardHeader><CardBody className="grid gap-4 sm:grid-cols-2"><Field label="Kickoff"><Input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)}/></Field><Field label="Venue"><Input value={venue} onChange={e=>setVenue(e.target.value)} placeholder="College football ground"/></Field><Button variant="outline" onClick={saveSetup} disabled={busy} className="sm:col-span-2">Save setup</Button></CardBody></Card>
 <Card><CardHeader><CardTitle>2. Cameras and ingest</CardTitle><p className="mt-1 text-sm text-muted">Add every phone before kickoff. FieldCast generates a unique Larix destination for each one.</p></CardHeader><CardBody><div className="mb-4 rounded-lg bg-surface-2 p-3 text-xs text-muted"><strong className="text-foreground">Recommended Larix settings:</strong> H.264, 1080p/30 fps, 4–6 Mbps, AAC audio, 2-second keyframe interval. Mount phones horizontally and disable auto-lock.</div><div className="space-y-3">{match.cameras.map(camera=><div key={camera.id} className="rounded-lg border border-border p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{camera.name} · {camera.angle}</p><p className="mt-1 break-all font-mono text-xs text-muted">{camera.ingestUrl}</p></div>{match.status==="live"&&<Button size="sm" variant={match.activeCamera===camera.streamKey?"primary":"outline"} onClick={()=>switchCamera(camera.streamKey)}>{match.activeCamera===camera.streamKey?"Active feed":"Take live"}</Button>}</div>{match.status!=="live"&&<button className="mt-2 text-xs text-red-600" onClick={async()=>setMatch(await api.removeMatchCamera(match.id,camera.id))}>Remove</button>}</div>)}</div>{match.status!=="live"&&<form onSubmit={addCamera} className="mt-4 grid gap-3 sm:grid-cols-2"><Input value={cameraName} onChange={e=>setCameraName(e.target.value)} placeholder="Camera 1" required/><Select value={angle} onChange={e=>setAngle(e.target.value)}><option>Main sideline</option><option>Opposite sideline</option><option>Behind home goal</option><option>Behind away goal</option><option>Commentary / wide safety</option></Select><Button type="submit" variant="outline" className="sm:col-span-2">Add camera</Button></form>}</CardBody></Card>
 <Card><CardHeader><CardTitle>3. Football broadcast preflight</CardTitle></CardHeader><CardBody className="space-y-3">{CHECKS.map(c=><label key={c.key} className="flex cursor-pointer gap-3 rounded-lg border border-border p-3"><input type="checkbox" checked={Boolean(checks[c.key])} onChange={e=>setChecks({...checks,[c.key]:e.target.checked})} className="mt-1 h-4 w-4 accent-accent"/><span><span className="text-sm font-medium">{c.label}</span><span className="mt-0.5 block text-xs text-muted">{c.hint}</span></span></label>)}<Button variant="outline" className="w-full" onClick={saveSetup}>Save preflight</Button></CardBody></Card></div>
 <div className="space-y-6"><Card><CardHeader><CardTitle>Update football scorecard</CardTitle><p className="mt-1 text-sm text-muted">Choose an event and a registered match player. Goals update the selected player&apos;s team score automatically.</p></CardHeader><CardBody><div className="grid grid-cols-2 gap-4"><Field label={match.teamA.name}><Input type="number" min={0} value={scoreA} onChange={e=>setScoreA(Number(e.target.value))}/></Field><Field label={match.teamB.name}><Input type="number" min={0} value={scoreB} onChange={e=>setScoreB(Number(e.target.value))}/></Field><Field label="Match event"><Select value={eventType} onChange={e=>setEventType(e.target.value)}><option value="goal">Goal</option><option value="yellow_card">Yellow card</option><option value="red_card">Red card</option><option value="substitution">Substitution</option></Select></Field><Field label="Half"><Select value={half} onChange={e=>setHalf(Number(e.target.value))}><option value={1}>First half</option><option value={2}>Second half</option></Select></Field><Field label="Minute"><Input type="number" min={0} max={120} value={minute} onChange={e=>setMinute(Number(e.target.value))}/></Field><Field label="Added-time minute" hint="For 45+2, enter minute 45 and added time 2."><Input type="number" min={0} max={30} value={extraTimeMinute} onChange={e=>setExtraTimeMinute(Number(e.target.value))}/></Field></div><PlayerSearch match={match} query={playerQuery} selectedPlayerId={selectedPlayerId} onQueryChange={value=>{setPlayerQuery(value);setSelectedPlayerId(null)}} onSelect={(playerId,label)=>{setSelectedPlayerId(playerId);setPlayerQuery(label)}}/>{success&&<p className="mt-4 rounded-lg bg-green-50 px-3 py-2 text-sm text-green-700">{success}</p>}<Button className="mt-4 w-full" onClick={updateScorecard} disabled={match.status!=="live"||!selectedPlayerId||busy}>{busy?"Updating…":"Update scorecard"}</Button></CardBody></Card>
 {match.status==="live"&&<Card><CardHeader><CardTitle>End match</CardTitle></CardHeader><CardBody><p className="text-sm text-muted">Ending the match stops live scoring and marks the fixture complete. You can confirm the winner and replay later.</p><Button variant="danger" className="mt-4 w-full" onClick={async()=>setMatch(await api.setMatchStatus(match.id,"completed"))}>End live match</Button></CardBody></Card>}</div></div></div>
}

function PlayerSearch({match,query,selectedPlayerId,onQueryChange,onSelect}:{match:Match;query:string;selectedPlayerId:number|null;onQueryChange:(value:string)=>void;onSelect:(playerId:number,label:string)=>void}){
 const [open,setOpen]=useState(false);
 const roster=[...(match.teamA.players||[]).map(membership=>({...membership,team:match.teamA})),...(match.teamB.players||[]).map(membership=>({...membership,team:match.teamB}))];
 const normalized=query.toLowerCase().trim();
 const filtered=roster.filter(({player,jerseyNumber,team})=>!normalized||player.name.toLowerCase().includes(normalized)||jerseyNumber.toLowerCase().includes(normalized)||team.shortName.toLowerCase().includes(normalized));
 const label=(entry:(typeof roster)[number])=>`#${entry.jerseyNumber} · ${entry.player.name} · ${entry.team.shortName}`;
 return <Field label="Player" hint="Search by player name, jersey number, or team short name." className="relative mt-4"><Input value={query} onFocus={()=>setOpen(true)} onBlur={()=>setOpen(false)} onChange={e=>{onQueryChange(e.target.value);setOpen(true)}} placeholder="Search registered match player…" autoComplete="off"/>{!selectedPlayerId&&open&&<div className="absolute left-0 right-0 top-full z-20 mt-1 max-h-56 overflow-y-auto rounded-lg border border-border bg-surface p-1 shadow-lg">{filtered.map(entry=><button type="button" key={`${entry.teamId}-${entry.playerId}`} onMouseDown={e=>e.preventDefault()} onClick={()=>{onSelect(entry.playerId,label(entry));setOpen(false)}} className="block w-full rounded-md px-3 py-2 text-left text-sm hover:bg-surface-2"><strong>#{entry.jerseyNumber}</strong> · {entry.player.name} · <span className="font-semibold text-accent">{entry.team.shortName}</span></button>)}{!filtered.length&&<p className="px-3 py-3 text-sm text-muted">No registered player found.</p>}</div>}</Field>
}
