"use client";

import { useCallback, useEffect, useState } from "react"; import Link from "next/link";
import { useAuth } from "@/hooks/useAuth"; import { api } from "@/lib/api"; import type { Match, Tournament } from "@/lib/types";
import { Button } from "@/ui/Button"; import { Card, CardBody, CardHeader, CardTitle } from "@/ui/Card"; import { Field } from "@/ui/Field"; import { Input, Select } from "@/ui/Input"; import { Badge } from "@/ui/Badge";

export default function OrganizerPage(){
 const {user,loading}=useAuth();const [tournaments,setTournaments]=useState<Tournament[]>([]);const [selectedId,setSelectedId]=useState(0);const [matches,setMatches]=useState<Match[]>([]);const [email,setEmail]=useState("");const [teamA,setTeamA]=useState("");const [teamB,setTeamB]=useState("");const [scheduledAt,setScheduledAt]=useState("");const [venue,setVenue]=useState("");const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 const selected=tournaments.find(t=>t.id===selectedId);
 const load=useCallback(async()=>{const data=await api.organizedTournaments();setTournaments(data);setSelectedId(current=>current||data[0]?.id||0);},[]);
 const loadMatches=useCallback(async()=>{if(selectedId)setMatches(await api.listMatches({tournamentId:String(selectedId)}));else setMatches([])},[selectedId]);
 useEffect(()=>{if(!user)return;const timer=window.setTimeout(()=>load().catch(e=>setError(e.message)),0);return()=>clearTimeout(timer)},[user,load]);
 useEffect(()=>{const timer=window.setTimeout(()=>loadMatches().catch(e=>setError(e.message)),0);return()=>clearTimeout(timer)},[loadMatches]);
 async function invite(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError("");try{const updated=await api.addOrganizer(selected.id,email);setTournaments(items=>items.map(t=>t.id===updated.id?updated:t));setEmail("")}catch(e){setError(e instanceof Error?e.message:"Could not add organiser")}finally{setBusy(false)}}
 async function createMatch(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError("");try{const match=await api.createMatch({tournamentId:selected.id,teamAId:Number(teamA),teamBId:Number(teamB),sport:selected.sport,scheduledAt,venue});window.location.assign(`/organizer/matches/${match.id}`)}catch(e){setError(e instanceof Error?e.message:"Could not create match")}finally{setBusy(false)}}
 if(loading)return <div className="py-24 text-center text-muted">Loading…</div>;if(!user)return <div className="py-24 text-center"><p className="text-muted">Log in to access organiser controls.</p><Link href="/auth" className="mt-4 inline-flex rounded-lg bg-accent px-4 py-2 font-semibold text-black">Log in</Link></div>;
 return <div className="mx-auto max-w-6xl px-4 py-10"><div className="mb-8"><p className="text-sm font-medium text-accent">Organiser workspace</p><h1 className="mt-1 text-2xl font-bold">Run your tournaments</h1><p className="mt-2 text-sm text-muted">Create fixtures, prepare cameras, start broadcasts, and manage live scorecards.</p></div>{error&&<p className="mb-5 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
 {!tournaments.length?<Card><CardBody className="py-16 text-center"><h2 className="font-semibold">No approved tournaments to manage</h2><p className="mt-2 text-sm text-muted">Once one of your submissions is approved, it will appear here and you will become its first organiser.</p></CardBody></Card>:<><Field label="Choose approved tournament" className="mb-6 max-w-md"><Select value={selectedId} onChange={e=>{setSelectedId(Number(e.target.value));setTeamA("");setTeamB("")}}>{tournaments.map(t=><option key={t.id} value={t.id}>{t.name} · {t.sport}</option>)}</Select></Field>
 {selected&&<div className="grid gap-6 lg:grid-cols-3"><div className="space-y-6 lg:col-span-2"><Card><CardHeader><CardTitle>Matches</CardTitle></CardHeader><CardBody><div className="space-y-3">{matches.map(m=><Link href={`/organizer/matches/${m.id}`} key={m.id} className="flex items-center justify-between rounded-lg border border-border p-4 transition-colors hover:border-accent"><div><p className="font-medium">{m.teamA.name} vs {m.teamB.name}</p><p className="mt-1 text-xs text-muted">{m.venue||"Venue pending"} · {m.cameras.length} camera{m.cameras.length===1?"":"s"}</p></div><Badge tone={m.status==="live"?"accent":"muted"}>{m.status}</Badge></Link>)}{!matches.length&&<p className="py-8 text-center text-sm text-muted">No matches created yet.</p>}</div></CardBody></Card>
 {selected.sport==="football"?<Card><CardHeader><CardTitle>Create football match</CardTitle><p className="mt-1 text-sm text-muted">Kickoff and venue are part of the required broadcast preflight.</p></CardHeader><CardBody><form onSubmit={createMatch} className="grid gap-4 sm:grid-cols-2"><Field label="Home team"><Select value={teamA} onChange={e=>setTeamA(e.target.value)} required><option value="">Choose team</option>{selected.teams.map(x=><option key={x.teamId} value={x.teamId}>{x.team.name}</option>)}</Select></Field><Field label="Away team"><Select value={teamB} onChange={e=>setTeamB(e.target.value)} required><option value="">Choose team</option>{selected.teams.filter(x=>String(x.teamId)!==teamA).map(x=><option key={x.teamId} value={x.teamId}>{x.team.name}</option>)}</Select></Field><Field label="Kickoff"><Input type="datetime-local" value={scheduledAt} onChange={e=>setScheduledAt(e.target.value)} required/></Field><Field label="Venue"><Input value={venue} onChange={e=>setVenue(e.target.value)} required placeholder="College football ground"/></Field><Button type="submit" disabled={busy} className="sm:col-span-2">Create match & prepare stream</Button></form></CardBody></Card>:<Card><CardBody className="py-10 text-center text-sm text-muted">The organiser broadcast setup is currently implemented for football. Other sports come next.</CardBody></Card>}</div>
 <div><Card><CardHeader><CardTitle>Organisers</CardTitle><p className="mt-1 text-sm text-muted">Everyone listed here can manage scores, cameras, and fixtures for this tournament.</p></CardHeader><CardBody><div className="space-y-3">{selected.organizers.map(o=><div key={o.userId}><p className="text-sm font-medium">{o.user.name||o.user.email}</p><p className="text-xs text-muted">{o.user.email}</p></div>)}</div><form onSubmit={invite} className="mt-5 space-y-3"><Field label="Add organiser by account email"><Input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="organiser@college.edu"/></Field><Button type="submit" variant="outline" className="w-full" disabled={busy}>Add organiser</Button></form></CardBody></Card></div></div>}</>}</div>
}
